server:
  port: 9021

spring:
  profiles:
    active: druid
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#  profiles:
#    active: dev
  application:
    name: estate-auth

  redis:
    host: 192.168.191.151
    port: 6379
    database: 6

    lettuce:
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0       # 连接池中的最小空闲连接
        max-idle: 8       # 连接池中的最大空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        time-between-eviction-runs: 100ms  # 连接超时时间（毫秒）

# 激活 sentinel 对 feign 的支持,必须有sentinel依赖
feign:
  sentinel:
    enabled: true

