server:
  port: 1213
#是否开启feign
feign:
  hystrix:
    enabled: true
  client:
    default:
      connect-timeout:20000
      read-timeout:30000
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zebra
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
#是否开启api秘钥验签
api:
  security:
    enabled: true
#server name
commodtidy:
  server:
    name: zebra-yritsz-api-commodity
order:
  server:
    name: zebra-yritsz-api-order
#seata
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_ruoyiplus_tx_group