server:
  port: 1213
feign:
  hystrix:
    enabled: true
  client:
    default:
      connect-timeout:20000
      read-timeout:30000
# MyBatis
mybatis:
    # \u641c\u7d22\u6307\u5b9a\u5305\u522b\u540d
    typeAliasesPackage: com.zebra
    # \u914d\u7f6emapper\u7684\u626b\u63cf\uff0c\u627e\u5230\u6240\u6709\u7684mapper.xml\u6620\u5c04\u6587\u4ef6
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # \u52a0\u8f7d\u5168\u5c40\u7684\u914d\u7f6e\u6587\u4ef6
    configLocation: classpath:mybatis/mybatis-config.xml
#\u662f\u5426\u5f00\u542fapi\u79d8\u94a5\u9a8c\u7b7e
api:
  security:
    enabled: true
#server name
commodtidy:
  server:
    name: zebra-yritsz-api-commodity
order:
  server:
    name: zebra-yritsz-api-order
#seata
spring: 
  cloud: 
    alibaba: 
      seata: 
        tx-service-group: my_ruoyiplus_tx_group
