#用于部署运行所依赖的服务
version: '3'
services:
  # MySQL数据库
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #设置root帐号密码
      TZ: Asia/Shanghai
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql #数据文件挂载
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d #配置文件挂载
      - ${MYSQL_LOG_DIR}:/var/log/mysql #日志文件挂载
  # Redis数据库
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ${REDIS_DATA_DIR}:/data #数据文件挂载
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf #配置文件挂载
    ports:
      - "${REDIS_HOST_PORT}:6379"
  # Nacos注册中心和配置中心
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
      - "PREFER_HOST_MODE=${PREFER_HOST_MODE}"
      - "MODE=${MODE}"
      - "SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM}"
      - "MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}"
      - "MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}"
      - "MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}"
      - "MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}"
      - "MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}"
    volumes:
      - ${NACOS_LOG_DIR}:/home/nacos/logs:rw #日志文件挂载
      - ${NACOS_CONF_DIR}:/home/nacos/init.d #配置文件挂载
    depends_on:
      - mysql
    expose:
      - 8848
    ports:
      - 8848:8848
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 3000:3000
  # volumes:
  #  - ./config.json:/yapi/config.json
    environment:
      - YAPI_ADMIN_ACCOUNT=******@qq.com
      - YAPI_ADMIN_PASSWORD=admin123
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=true
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - mongo
    privileged: true
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - D:\docker\mongodb\data\db:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    depends_on:
      - nginx
    privileged: true
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: always
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    volumes:
      - D:\docker\nginx\configs\:/etc/nginx/conf.d/
